### ISSUE TITLE
v2.0.2 merge checklist

### ISSUE THREAD

**Issue by shu8** [soscripted/sox#169]
### v2.0.2  @soscripted/admins

- [x] Tested on Chrome
- [x] Tested on Firefox
- [x] Confirm access token can be made and saved automatically
- [x] Verify all features working correctly
- [x] Check console for errors
- [x] Update features list in Features Wiki (_update old descriptions_)
- [x] Update Contributing Wiki to reflect the latest structure
- [x] Update Contributing Wiki to reflect new helper functions

**Comment by shu8** [comment]
V2.0.2 has been pushed to master.
